name: pr check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CYPRESS_INSTALL_BINARY: "0"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      NX_DAEMON: "false"

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.33.7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "source/pnpm-lock.yaml"

      - run: node ./scripts/ci.js
